# Generated by Django 5.0.2 on 2024-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'catalogo',
                'verbose_name_plural': 'catalogo',
                'db_table': 'catalogos',
                'managed': True,
            },
        ),
    ]
