# Generated by Django 5.0.2 on 2024-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=100)),
                ('es_superusuario', models.IntegerField(default=0, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('etnia', models.CharField(max_length=50)),
                ('discapacidad', models.CharField(max_length=5)),
                ('recibir_informacion', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuario',
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
